### ISSUE TITLE
Coverage tests hangs up

### ISSUE THREAD

**Issue by rtorino** [dylanb/gulp-coverage#39] opened 2015-04-15 08:13 UTC
gulp-coverage unable to create the `coverage.html` reporter file and my coverage test hangs up. I am using mocha as test runner. Below is my gulpfile.js:

```javascript
gulp.src( tests, { 'read' : false } )

		.pipe( cover.instrument( {
			'pattern'        : [ handlers, services ],
			'debugDirectory' : 'instrumented'
		} ) )

		.pipe( mocha( options ) )

		.pipe( cover.gather() )

		.pipe( cover.format( {
			'reporter' : 'html',
			'outFile'  : 'coverage.html'
		} ) )

		.pipe( cover.enforce( {
			'statements' : 70,
			'blocks'     : 70,
			'lines'      : 70
		} ) )

		.once( 'error', function () {
			process.exit( 1 );
		} )
		
		.once( 'end', function () {
			process.exit();
		} );
```

**Comment by dylanb** [comment] 2015-04-15 12:54
Can you provide a stripped-down gulp file with source code files that reproduces the problem?

If not, can you provide more information? For example: what `handlers` and `services` are set to? What the directory structure of the project is, what modules are included in the gulp script etc.

Also:

What output are you seeing? Does Gulp output anything at all?

**Comment by dylanb** [comment] 2015-04-23 02:58
Closing this issue due to inability to reproduce. If you provide the info, I will re-open.

**Closed by dylanb** 2015-04-23 02:58 UTC
